name: 🪲报告 BUG
description: 报告一个 BUG, 来帮助我们改进该程序。
title: "[Bug]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        #### ⚠️须知：
        1. 请一次只提交一个 BUG;
        2. 过度久远的版本的 BUG 不会被受理[^注];
        3. 请尽量详细为我们提供相关信息;
        4. 请确保您所提供的信息真实;
        5. 填写该 Issue 需要一点计算机知识储备;
        6. 依赖正确安装, 且 Python 版本不低于要求最低版本;
        7. 做到能在发布该 Issue 后能依据开发者要求进行信息提供。
        [^注]: 现指1.x、2.x的所有版本

  - type: markdown
    attributes:
      value: |
        ## BUG 信息：
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请告诉我们在你预期中会发生什么?(如果有截图或视频更好)
      placeholder: 支持 Markdown, 请在此处填写
    validations:
      required: true
  - type: textarea
    id: ways-to-happen
    attributes:
      label: 如何复现？
      description: 尽可能详细得告诉我们如何复现(如果有截图或视频更好, 若可以提交日志, 则无需填写)
      placeholder: 支持 Markdown, 请在此处填写
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: 日志
      description: 如果使用的版本大于或等于v3.5p, 请使用终端软件打开程序, 复现操作 BUG 发生后将所有内容都添加到此处
      placeholder: 支持 Markdown, 请在此处填写
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 版本信息：
  - type: input
    id: version
    attributes:
      label: 程序版本：
      description: 请提供您所使用的程序版本(示例“v3.0p”), 若是直接下载源码运行, 请填写 Commit 号(示例“866b6fd”)
      placeholder: v3.0p
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 请提供您的运行平台：
      multiple: true
      options:
        - Windows 
        - Linux
        - macOS
        - BSD(包括OpenBSD, NetBSD, FreeBSD)
        - 其他
    validations:
      required: true
  - type: input
    id: platform-ver
    attributes:
      label: 系统版本：
      description: 请输入您所使用系统的具体名称, 越具体越好(如果信息不全可能会被追问), 如：Fedora Workstation 37; Windows 11 Canary 25381; macOS Ventura 22F66
      placeholder: Windows 11 Canary 25381
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: 请提供您的运行平台架构信息：
      multiple: true
      options:
        - x86 
        - x86_64
        - arm
        - arm64
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 杂项：
  - type: textarea
    id: notes
    attributes:
      label: 备注(可选)
      description: 还有什么要补充? 您可以在这里提供更详细的内容, 或者提供您所认为的解决方案, 当然其他信息也行
      placeholder: 支持 Markdown, 请在此处填写
    validations:
      required: false
  - type: checkboxes
    id: allow
    attributes:
      label: 发布前确定
      description: 发布该 Issue 前, 请确保您提交的内容符合须知要求, 否则我们将会 Close 该 Issue!
      options:
        - label: 我接受
          required: true
